# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20161108_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Section number'),
        ),
    ]
