# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_auto_20161108_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Chapter number'),
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Section number'),
        ),
    ]
