# Generated by Django 2.0.9 on 2018-10-09 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0009_auto_20181006_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
