# Generated by Django 2.0.9 on 2018-10-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0013_auto_20181011_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
