# Generated by Django 2.0.9 on 2018-10-12 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0014_auto_20181011_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='importers',
            field=models.ManyToManyField(related_name='importers', to=settings.AUTH_USER_MODEL),
        ),
    ]
