# Generated by Django 2.0.9 on 2018-10-25 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0023_auto_20181025_1846'),
        ('campaign', '0015_auto_20181012_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='monster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.Monster'),
        ),
        migrations.AddField(
            model_name='review',
            name='npc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.NPC'),
        ),
        migrations.AddField(
            model_name='review',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.Player'),
        ),
        migrations.AlterField(
            model_name='review',
            name='campaign',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign'),
        ),
    ]
