# Generated by Django 2.0.9 on 2018-10-25 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0016_auto_20181025_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='review',
            name='monster',
        ),
        migrations.RemoveField(
            model_name='review',
            name='npc',
        ),
        migrations.RemoveField(
            model_name='review',
            name='player',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
