# Generated by Django 3.2.6 on 2021-08-17 14:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0018_auto_20210810_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('public_id', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('data', models.JSONField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign')),
            ],
        ),
    ]
