# Generated by Django 3.2.6 on 2021-08-17 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0019_campaignexport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignexport',
            name='data',
        ),
    ]
