# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='charisma',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='monster',
            name='constitution',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='monster',
            name='dexterity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='monster',
            name='intelligence',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='monster',
            name='strength',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='monster',
            name='wisdom',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='npc',
            name='charisma',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='npc',
            name='constitution',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='npc',
            name='dexterity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='npc',
            name='intelligence',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='npc',
            name='strength',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='npc',
            name='wisdom',
            field=models.IntegerField(default=1),
        ),
    ]
