# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_auto_20161107_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='languages',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='monster',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='monster',
            name='saving_throws',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='monster',
            name='skills',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='monster',
            name='speed',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='npc',
            name='languages',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='npc',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='npc',
            name='saving_throws',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='npc',
            name='skills',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='npc',
            name='speed',
            field=models.CharField(default='', max_length=255),
        ),
    ]
