# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_auto_20161107_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='actions',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='monster',
            name='challenge_rating',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='monster',
            name='condition_immunities',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='monster',
            name='damage_immunities',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='monster',
            name='damage_vulnerabilities',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='monster',
            name='senses',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='monster',
            name='traits',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='npc',
            name='actions',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='npc',
            name='age',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='npc',
            name='challenge_rating',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='npc',
            name='condition_immunities',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='npc',
            name='creature_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='npc',
            name='damage_immunities',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='npc',
            name='damage_vulnerabilities',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='npc',
            name='height',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='npc',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='npc',
            name='personality_traits',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='npc',
            name='senses',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='npc',
            name='traits',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='npc',
            name='weight',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='monster',
            name='creature_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='npc',
            name='npc_class',
            field=models.CharField(default='', max_length=255),
        ),
    ]
