# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_auto_20161121_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='armor_class',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monster',
            name='challenge_rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='monster',
            name='charisma',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='monster',
            name='constitution',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='monster',
            name='dexterity',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='monster',
            name='hit_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monster',
            name='intelligence',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='monster',
            name='languages',
            field=models.CharField(default='Common', max_length=255),
        ),
        migrations.AlterField(
            model_name='monster',
            name='strength',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='monster',
            name='wisdom',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='npc',
            name='armor_class',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='npc',
            name='charisma',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='npc',
            name='constitution',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='npc',
            name='dexterity',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='npc',
            name='hit_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='npc',
            name='intelligence',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='npc',
            name='languages',
            field=models.CharField(default='Common', max_length=255),
        ),
        migrations.AlterField(
            model_name='npc',
            name='strength',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='npc',
            name='wisdom',
            field=models.IntegerField(default=10),
        ),
    ]
