# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_auto_20161127_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='actions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='traits',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='npc',
            name='actions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='npc',
            name='traits',
            field=models.TextField(blank=True),
        ),
    ]
