# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_auto_20161127_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npc',
            name='personality_traits',
        ),
        migrations.AlterField(
            model_name='npc',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
