# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_auto_20161127_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='npc_class',
            field=models.CharField(default='', max_length=255, verbose_name='Class'),
        ),
    ]
