# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_auto_20161128_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='armor_class',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='monster',
            name='challenge_rating',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='monster',
            name='charisma',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='monster',
            name='condition_immunities',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='monster',
            name='constitution',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='monster',
            name='creature_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='monster',
            name='damage_immunities',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='monster',
            name='damage_vulnerabilities',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='monster',
            name='dexterity',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='monster',
            name='hit_points',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='monster',
            name='intelligence',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='monster',
            name='saving_throws',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='monster',
            name='senses',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='monster',
            name='skills',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='monster',
            name='speed',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='monster',
            name='strength',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='monster',
            name='wisdom',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='npc',
            name='age',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='npc',
            name='armor_class',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='npc',
            name='challenge_rating',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='npc',
            name='charisma',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='npc',
            name='condition_immunities',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='npc',
            name='constitution',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='npc',
            name='creature_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='npc',
            name='damage_immunities',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='npc',
            name='damage_vulnerabilities',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='npc',
            name='dexterity',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='npc',
            name='height',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='npc',
            name='hit_points',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='npc',
            name='intelligence',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='npc',
            name='npc_class',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='saving_throws',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='npc',
            name='senses',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='npc',
            name='skills',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='npc',
            name='speed',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='npc',
            name='strength',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='npc',
            name='weight',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='npc',
            name='wisdom',
            field=models.IntegerField(blank=True, default=10),
        ),
    ]
