# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_auto_20161211_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='alignment',
            field=models.CharField(choices=[('Unaligned', 'Unaligned'), ('LG', 'Lawful Good'), ('NG', 'Neutral Good'), ('CG', 'Chaotic Good'), ('LN', 'Lawful Neutral'), ('N', 'Neutral'), ('CN', 'Chaotic Neutral'), ('LE', 'Lawful Evil'), ('NE', 'Neutral Evil'), ('CE', 'Chaotic Evil')], default='Neutral', max_length=255),
        ),
        migrations.AlterField(
            model_name='monster',
            name='languages',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='npc',
            name='alignment',
            field=models.CharField(choices=[('Unaligned', 'Unaligned'), ('LG', 'Lawful Good'), ('NG', 'Neutral Good'), ('CG', 'Chaotic Good'), ('LN', 'Lawful Neutral'), ('N', 'Neutral'), ('CN', 'Chaotic Neutral'), ('LE', 'Lawful Evil'), ('NE', 'Neutral Evil'), ('CE', 'Chaotic Evil')], default='Neutral', max_length=255),
        ),
        migrations.AlterField(
            model_name='npc',
            name='languages',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
