# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0012_auto_20161212_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='challenge_rating',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='monster',
            name='hit_points',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='npc',
            name='age',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='npc',
            name='hit_points',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
