# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0013_auto_20161212_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='damage_resistances',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
        migrations.AddField(
            model_name='npc',
            name='damage_resistances',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
    ]
