# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0014_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='actions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='background',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='bonds',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='feats',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='flaws',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='ideals',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='personality',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='player',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='player_class',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='proficiency',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='race',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='senses',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='spells',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='traits',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='xp',
            field=models.IntegerField(blank=True, default=10),
        ),
    ]
