# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-22 15:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('characters', '0014_auto_20161215_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('level', models.IntegerField(default=1)),
                ('alignment', models.CharField(choices=[('Unaligned', 'Unaligned'), ('LG', 'Lawful Good'), ('NG', 'Neutral Good'), ('CG', 'Chaotic Good'), ('LN', 'Lawful Neutral'), ('N', 'Neutral'), ('CN', 'Chaotic Neutral'), ('LE', 'Lawful Evil'), ('NE', 'Neutral Evil'), ('CE', 'Chaotic Evil')], default='Neutral', max_length=255)),
                ('size', models.CharField(choices=[('Tiny', 'Tiny'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Huge', 'Huge'), ('Gargantuan', 'Gargantuan')], default='Medium', max_length=255)),
                ('languages', models.CharField(blank=True, max_length=255)),
                ('strength', models.IntegerField(blank=True, default=10)),
                ('dexterity', models.IntegerField(blank=True, default=10)),
                ('constitution', models.IntegerField(blank=True, default=10)),
                ('intelligence', models.IntegerField(blank=True, default=10)),
                ('wisdom', models.IntegerField(blank=True, default=10)),
                ('charisma', models.IntegerField(blank=True, default=10)),
                ('armor_class', models.IntegerField(blank=True, default=0)),
                ('hit_points', models.CharField(blank=True, max_length=255)),
                ('speed', models.CharField(blank=True, default='', max_length=255)),
                ('saving_throws', models.CharField(blank=True, default='', max_length=255)),
                ('skills', models.CharField(blank=True, default='', max_length=255)),
                ('character_name', models.CharField(default='', max_length=255)),
                ('proficiency_bonus', models.CharField(blank=True, default='', max_length=255)),
                ('player_name', models.CharField(blank=True, default='', max_length=255)),
                ('character_class', models.CharField(blank=True, default='', max_length=255)),
                ('race', models.CharField(blank=True, default='', max_length=255)),
                ('xp', models.IntegerField(blank=True, default=0, verbose_name='XP')),
                ('background', models.CharField(blank=True, default='', max_length=255)),
                ('age', models.CharField(blank=True, default='', max_length=255)),
                ('height', models.CharField(blank=True, default='', max_length=255)),
                ('weight', models.CharField(blank=True, default='', max_length=255)),
                ('initiative', models.CharField(blank=True, default='', max_length=255)),
                ('personality', models.TextField(blank=True)),
                ('bonds', models.TextField(blank=True)),
                ('ideals', models.TextField(blank=True)),
                ('flaws', models.TextField(blank=True)),
                ('feats', models.TextField(blank=True)),
                ('attacks', models.TextField(blank=True)),
                ('spells', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('traits', models.TextField(blank=True)),
                ('proficiencies', models.TextField(blank=True)),
                ('senses', models.CharField(blank=True, default='', max_length=255)),
                ('equipment', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='monster',
            name='damage_resistances',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='npc',
            name='damage_resistances',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
