# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-22 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0015_auto_20161222_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
