# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-30 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0016_monster_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='armor_class',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='npc',
            name='armor_class',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='armor_class',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
