# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-09 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0017_auto_20161230_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='race',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
