# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-11 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0018_npc_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='xp',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='XP'),
        ),
    ]
