# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-03 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_auto_20180403_1802'),
        ('characters', '0019_auto_20180311_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='campaigns',
            field=models.ManyToManyField(to='campaign.Campaign'),
        ),
    ]
