# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-04 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0020_player_campaigns'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
