# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-05 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0021_auto_20181004_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='actions',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='traits',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='actions',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='traits',
        ),
    ]
