# Generated by Django 2.0.9 on 2018-10-25 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('characters', '0022_auto_20181005_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='importers',
            field=models.ManyToManyField(related_name='monster_importers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monster',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monster',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='tavern_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='importers',
            field=models.ManyToManyField(related_name='npc_importers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='npc',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='npc',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='tavern_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='importers',
            field=models.ManyToManyField(related_name='player_importers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='player',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tavern_description',
            field=models.TextField(blank=True),
        ),
    ]
