# Generated by Django 2.0.9 on 2018-11-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0024_auto_20181111_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalcharacter',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generalcharacter',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalcharacter',
            name='tavern_description',
            field=models.TextField(blank=True),
        ),
    ]
