# Generated by Django 2.0.9 on 2018-11-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0017_auto_20181025_2026'),
        ('characters', '0026_generalcharacter_importers'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalcharacter',
            name='campaigns',
            field=models.ManyToManyField(to='campaign.Campaign'),
        ),
    ]
