# Generated by Django 2.0.9 on 2018-12-28 21:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0027_generalcharacter_campaigns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalcharacter',
            name='campaigns',
            field=models.ManyToManyField(blank=True, to='campaign.Campaign'),
        ),
        migrations.AlterField(
            model_name='generalcharacter',
            name='importers',
            field=models.ManyToManyField(blank=True, related_name='character_importers', to=settings.AUTH_USER_MODEL),
        ),
    ]
