# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-09 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_auto_20180309_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='new',
            field=models.BooleanField(default=False),
        ),
    ]
