# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-04 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20181002_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='tableoption',
            old_name='description',
            new_name='content',
        ),
    ]
