# Generated by Django 2.0.9 on 2018-11-12 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0025_auto_20181111_1624'),
        ('tavern', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.GeneralCharacter'),
        ),
    ]
