# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-14 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='world',
            name='user',
        ),
        migrations.RemoveField(
            model_name='location',
            name='world',
        ),
        migrations.AddField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
        migrations.DeleteModel(
            name='World',
        ),
    ]
