# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-30 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import locations.models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_parent_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to=locations.models.upload_to),
        ),
        migrations.AddField(
            model_name='world',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to=locations.models.upload_to),
        ),
    ]
