# Generated by Django 3.2.11 on 2022-03-01 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resourceattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.resource'),
        ),
        migrations.DeleteModel(
            name='ResourceAttribute',
        ),
    ]
