attrs = [
    'Name',
    'Level',
    'Alignment',
    'Size',
    'Languages',
    'Strength',
    'Dexterity',
    'Constitution',
    'Intelligence',
    'Wisdom',
    'Charisma',
    'Armor class',
    'Hit points',
    'Speed',
    'Saving throws',
    'Skills',
    'Class',
    'Race',
    'Age',
    'Height',
    'Weight',
    'Creature type',
    'Damage vulnerabilities',
    'Damage immunities',
    'Damage resistances',
    'Condition immunities',
    'Senses',
    'Challenge rating',
    'Proficiency bonus',
    'Experience points',
    'Background',
    'Age',
    'Height',
    'Weight',
    'Initiative',
    'Personality',
    'Bonds',
    'Ideals',
    'Flaws',
    'Feats',
    'Attack',
    'Spell',
    'Traits',
    'Proficiencies',
    'Senses',
    'Equipment',
]




