attrs = [
    'Name',
    'Level',
    'Alignment',
    'Size',
    'Languages',
    'Strength',
    'Dexterity',
    'Constitution',
    'Intelligence',
    'Wisdom',
    'Charisma',
    'Armor class',
    'Hit points',
    'Speed',
    'Saving throws',
    'Skills',
    'Class',
    'Race',
    'Character type',
    'Damage vulnerabilities',
    'Damage immunities',
    'Damage resistances',
    'Condition immunities',
    'Challenge rating',
    'Proficiency bonus',
    'Experience points',
    'Background',
    'Age',
    'Height',
    'Weight',
    'Initiative',
    'Personality',
    'Bonds',
    'Ideals',
    'Flaws',
    'Feats',
    'Attack',
    'Spell',
    'Traits',
    'Proficiencies',
    'Senses',
    'Equipment',
]




